### ISSUE TITLE
@route + way of accessing corepost class instance attributes

### ISSUE THREAD

**Issue by kaosat-dev** [jacek99/corepost#3]
Hi Jacek!

I am currently giving Corepost a try (great set of features !),  and the problem is , I see no way of passing additional data to a CorePost class instance so that it can be reused in the routed methods: ie for example, this fails:

class HomeApp(CorePost):
    def **init**(self,_args,__kwargs):
        CorePost.**init**(self, *args, *_kwargs)
        self.thing = "a test"

```
@route("/",Http.GET)
def root(self,request,**kwargs):
    print (self.thing)
    return request.path
```

Inside the decorated method, "self" points to a RequestRouter instance , so is there any workaround /change to the decorators that can keep the "self" inside the method referring to the CorePost /CorePost subclass instance ?

**Comment by jacek99** [comment]
Let me look into this. I will try to come up with a solution

**Comment by jacek99** [comment]
Fixed in 0.0.9

**Comment by kaosat-dev** [comment]
that was amazingly fast, thanks a lot ! will give it a try tonight!

**Comment by kaosat-dev** [comment]
works like a charm, thanks once again!
