### ISSUE TITLE
Bug in test rest_resource.py

### ISSUE THREAD

**Issue by klinkin** [jacek99/corepost#4]
Hi Jacek!

I am currently trying Corepost and find a bug in test https://github.com/jacek99/corepost/blob/master/corepost/test/rest_resource.py

If i try [http://localhost:8085/customer/1](http://localhost:8085/customer/1), 
i get 
`Unexpected server error: <class 'jinja2.exceptions.UndefinedError'>
'str object' has no attribute 'iteritems'`

**Comment by jacek99** [comment]
cool :-) 
I will fix it ASAP. I thought  had removed all Jinja2 references, it was just a short lived experiment....

**Comment by jacek99** [comment]
Hi, which version are you using? I just verified the latest code in github and it works just fine, no jinja2 errors...

**Comment by klinkin** [comment]
Very strange, I use last version (git clone git://github.com/jacek99/corepost.git)
I tried again and got the same result:(

**Comment by jacek99** [comment]
Bizarre. Do all the unit tests run fine for you?

From root folder run

nosetests --with-freshen

(assuming you did easy_install freshen)

**Comment by klinkin** [comment]
it's output from nosetests --with-freshen
https://gist.github.com/2401397

**Comment by jacek99** [comment]
OK, the first one is expected (different version of libs, I needed to tighten up the test to avoid checking for that).

The unicode ones are interesting. I don't see them on any of my Linux boxes (and I run this on 3 different distributions).
I know nothing about OS X though. Does it have some specific environment variables that affect Unicode settings in a shell?

**Comment by jacek99** [comment]
Also, what is the default version of Python that OS X ships with?

**Comment by jacek99** [comment]
Can you tell me what values you used to create customer #1? I think that would help me. I realized in my code I do use Jinja2 when trying to convert a class to XML format (instead of the default JSON), so that may be the culprit here...does your HTTP testing tool accept XML as default instead of JSON

**Comment by klinkin** [comment]
To create new customer i use https://addons.mozilla.org/ru/firefox/addon/poster/
i post request with body "customerId=1&firstName=Mike&lastName=Klimin"

after that in browser i check the url http://localhost:8085/customer
and get xml: 
https://gist.github.com/2401915

**Comment by jacek99** [comment]
Ah, so you are doing it from the browser, which by default can only accept HTML, vs the usual curl testing I do with JSON as the default output. I will try to replicate this in a BDD test and issue a fix shortly.

**Comment by klinkin** [comment]
Ufff :)) thanks Jacek!

**Comment by jacek99** [comment]
fixed in 0.0.16, pls verify. See new @issue4 BDD in rest_app.feature. Greatly improved serializing object graphs to XML in general, thanks to a good ActiveState recipe I found for this
