### ISSUE TITLE
multiple routes

### ISSUE THREAD

**Issue by llonchj** [jacek99/corepost#8]
Should something like this work? It makes any sense?

``` python
@route("/config/<pk>", Http.GET)
@route("/config", Http.GET)
def get_config(self, request, pk="default", **kwargs):
    return dict(self.root.config[pk])
```

**Comment by jacek99** [comment]
Hm, I think for code clarity I would prefer not to support this. One method per URL handler seems easier to understand.

ALso usually GET / should return a list (usually) while GET/<pk> a single instance. It feels like you are mixing two very different REST operations together.

**Comment by llonchj** [comment]
That's fine
